/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateTodoItemArgs } from "./CreateTodoItemArgs";
import { UpdateTodoItemArgs } from "./UpdateTodoItemArgs";
import { DeleteTodoItemArgs } from "./DeleteTodoItemArgs";
import { TodoItemCountArgs } from "./TodoItemCountArgs";
import { TodoItemFindManyArgs } from "./TodoItemFindManyArgs";
import { TodoItemFindUniqueArgs } from "./TodoItemFindUniqueArgs";
import { TodoItem } from "./TodoItem";
import { TodoList } from "../../todoList/base/TodoList";
import { TodoItemService } from "../todoItem.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => TodoItem)
export class TodoItemResolverBase {
  constructor(
    protected readonly service: TodoItemService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "TodoItem",
    action: "read",
    possession: "any",
  })
  async _todoItemsMeta(
    @graphql.Args() args: TodoItemCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [TodoItem])
  @nestAccessControl.UseRoles({
    resource: "TodoItem",
    action: "read",
    possession: "any",
  })
  async todoItems(
    @graphql.Args() args: TodoItemFindManyArgs
  ): Promise<TodoItem[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => TodoItem, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "TodoItem",
    action: "read",
    possession: "own",
  })
  async todoItem(
    @graphql.Args() args: TodoItemFindUniqueArgs
  ): Promise<TodoItem | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => TodoItem)
  @nestAccessControl.UseRoles({
    resource: "TodoItem",
    action: "create",
    possession: "any",
  })
  async createTodoItem(
    @graphql.Args() args: CreateTodoItemArgs
  ): Promise<TodoItem> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        listId: {
          connect: args.data.listId,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => TodoItem)
  @nestAccessControl.UseRoles({
    resource: "TodoItem",
    action: "update",
    possession: "any",
  })
  async updateTodoItem(
    @graphql.Args() args: UpdateTodoItemArgs
  ): Promise<TodoItem | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          listId: {
            connect: args.data.listId,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => TodoItem)
  @nestAccessControl.UseRoles({
    resource: "TodoItem",
    action: "delete",
    possession: "any",
  })
  async deleteTodoItem(
    @graphql.Args() args: DeleteTodoItemArgs
  ): Promise<TodoItem | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => TodoList, {
    nullable: true,
    name: "listId",
  })
  @nestAccessControl.UseRoles({
    resource: "TodoList",
    action: "read",
    possession: "any",
  })
  async resolveFieldListId(
    @graphql.Parent() parent: TodoItem
  ): Promise<TodoList | null> {
    const result = await this.service.getListId(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
