/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TodoListService } from "../todoList.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TodoListCreateInput } from "./TodoListCreateInput";
import { TodoListWhereInput } from "./TodoListWhereInput";
import { TodoListWhereUniqueInput } from "./TodoListWhereUniqueInput";
import { TodoListFindManyArgs } from "./TodoListFindManyArgs";
import { TodoListUpdateInput } from "./TodoListUpdateInput";
import { TodoList } from "./TodoList";
import { TodoItemFindManyArgs } from "../../todoItem/base/TodoItemFindManyArgs";
import { TodoItem } from "../../todoItem/base/TodoItem";
import { TodoItemWhereUniqueInput } from "../../todoItem/base/TodoItemWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TodoListControllerBase {
  constructor(
    protected readonly service: TodoListService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TodoList })
  @nestAccessControl.UseRoles({
    resource: "TodoList",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: TodoListCreateInput): Promise<TodoList> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TodoList] })
  @ApiNestedQuery(TodoListFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TodoList",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<TodoList[]> {
    const args = plainToClass(TodoListFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TodoList })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TodoList",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: TodoListWhereUniqueInput
  ): Promise<TodoList | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TodoList })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TodoList",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: TodoListWhereUniqueInput,
    @common.Body() data: TodoListUpdateInput
  ): Promise<TodoList | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TodoList })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TodoList",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: TodoListWhereUniqueInput
  ): Promise<TodoList | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/todoItems")
  @ApiNestedQuery(TodoItemFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TodoItem",
    action: "read",
    possession: "any",
  })
  async findManyTodoItems(
    @common.Req() request: Request,
    @common.Param() params: TodoListWhereUniqueInput
  ): Promise<TodoItem[]> {
    const query = plainToClass(TodoItemFindManyArgs, request.query);
    const results = await this.service.findTodoItems(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        listId: {
          select: {
            id: true,
          },
        },

        text: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/todoItems")
  @nestAccessControl.UseRoles({
    resource: "TodoList",
    action: "update",
    possession: "any",
  })
  async connectTodoItems(
    @common.Param() params: TodoListWhereUniqueInput,
    @common.Body() body: TodoItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      todoItems: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/todoItems")
  @nestAccessControl.UseRoles({
    resource: "TodoList",
    action: "update",
    possession: "any",
  })
  async updateTodoItems(
    @common.Param() params: TodoListWhereUniqueInput,
    @common.Body() body: TodoItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      todoItems: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/todoItems")
  @nestAccessControl.UseRoles({
    resource: "TodoList",
    action: "update",
    possession: "any",
  })
  async disconnectTodoItems(
    @common.Param() params: TodoListWhereUniqueInput,
    @common.Body() body: TodoItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      todoItems: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
